### ISSUE TITLE
Path lookup in compilerResult.files[key] is failing on windows.

### ISSUE THREAD

**Issue by stfnbrgh** [mologie/meteor-typescript#2] opened 2015-04-09 12:17 UTC
Hi Mologie,

I initially developed on linux and with the official windows meteor support  moved my project over to windows. However your compiler started failing with "Something is broken. Empty data or source map. (This is probably not your fault.)" errors.

After a brief browse in your code it seems that the suspect is windows vs linux path styles.

compilerStep.inputPath provides paths using backslashes ("backslash\style\path") but the key in compilerResult.files have forward slashes ("forwardslash/style/path"). This results in compilerResult.files[jsPath]  and compilerResult.files[jsPath+".map"] being undefined, and the sanity check failing.

I fixed (hacked) this by replacing all the \ with / of the compilerStep.inputPath inside the compileTypeScriptImpl function.

```
...
function compileTypeScriptImpl(compileStep) {                                                                         // 489
    compileStep.inputPath = compileStep.inputPath.replace(/\\/g, "/"); // Replace all \ with /                        // ADDED
    var prefix = makeDebugPrefix();                                                                                   // 490
...
```

This hack fixed your compiler package on windows. But I thought an issue might be more appropriate than a pull request as you will have deeper insight on the problem

Hope to hear from you soon.

Kind regards
Stefan

**Comment by mologie** [comment] 2015-04-09 13:14
Hello Stafan,

thank you for your detailed report. I can confirm this issue on my Windows 8.1 machine.

It turns out that the TypeScript compiler internally works with forward slashes only (and for the sake of compatibility with WScript does not use node's path module either, which I wrongly assumed it did). [TypeScript 1.5 behaves the same way.](https://github.com/Microsoft/TypeScript/blob/e925aa77b2838bd620ad9b79472d295b28c3be33/src/compiler/core.ts#L433-L481)

I think that your approach/workaround is the right way to solve this issue if one considers that all that has to be done is to be compatible with both TypeScript and Meteor. Just to be on the safe side, I will pass a path with backslashes back to Meteor as that's what Meteor gives my plugin.

Regards,
Oliver

**Comment by mologie** [comment] 2015-04-09 14:01
This issue is fixed in master now. I will push to Atmosphere after making sure that I did not break anything on *nix.

**Comment by mologie** [comment] 2015-04-09 14:25
Version 0.0.8 is now live on Atmosphere.

**Closed as completed by mologie** 2015-04-09 14:25 UTC
Labels: bug, confirmed
